<?php
class Car {
    public string $brand;
    public string $model;
    public int $numDoors;

    public function __construct(string $brand, string $model, int $numDoors) {
        $this->brand = $brand;
        $this->model = $model;
        $this->numDoors = $numDoors;
    }

    public function getDetails(): string {
        return "Car: {$this->brand} {$this->model}, Doors: {$this->numDoors}";
    }
}

class Motorcycle {
    public string $brand;
    public string $model;
    public bool $hasSidecar;

    public function __construct(string $brand, string $model, bool $hasSidecar) {
        $this->brand = $brand;
        $this->model = $model;
        $this->hasSidecar = $hasSidecar;
    }

    public function getDetails(): string {
        return "Motorcycle: {$this->brand} {$this->model}, Sidecar: " . ($this->hasSidecar ? "Yes" : "No");
    }
}

//$car = new Car("Toyota", "Corolla", 4);
//echo $car->getDetails() . "<br>";

//$motorcycle = new Motorcycle("Harley-Davidson", "Street 750", true);
//echo $motorcycle->getDetails();

//////////////////// الكود المعدل //////////////////

class Details{
    public string $name;
    public string $brand;
    public string $model;

    public function __construct(string $name,string $brand,string $model)
    {
        $this->name = $name;
        $this->brand = $brand;
        $this->model = $model;
    }

    public function getDetails():string
    {
        return "Name : {$this->name},Brand : {$this->brand} ,Model : {$this->model} ";
    }

}

class CarCode extends Details{
    private int $numDoors;
    public function __construct($name, $brand, $model,$numDoors)
    {
        parent::__construct($name, $brand, $model);
        $this->numDoors = $numDoors;
    }

    public function getDetails(): string
    {
        return parent::getDetails()."Doors : {$this->numDoors}"; // TODO: Change the autogenerated stub
    }
}

class MotorcycleCode extends Details{
    private bool $hasSidecar;
    public string $speed;
    public function __construct($name, $brand, $model,$hasSidecar)
    {
        parent::__construct($name, $brand, $model);
        $this->hasSidecar = $hasSidecar;
    }

    public function getDetails(): string
    {
        $sidecar =$this->hasSidecar ? "yes" :"no";
        return parent::getDetails()."Sidecar : {$sidecar}"; // TODO: Change the autogenerated stub
    }
}

$car = new CarCode('car','jep','25',4);
echo $car->getDetails()."<br>";
$motor = new MotorcycleCode('Motorcycle','vv','vv25',true);
echo $motor->getDetails()."<br>";
echo $motor->speed ="100cc";