<?php
class Vehicle {
   protected string $brand;
   protected string $model;

   public function __construct(string $brand,string $model)
   {
       $this->brand = $brand;
       $this->model = $model;
   }

   public function getDetails(): string{
       return "Brand : {$this->brand} ,Model: {$this->model}";
   }
}

class Car extends Vehicle{
     private int $numDoors;

     public function __construct($brand, $model,$numDoors)
     {
         parent::__construct($brand, $model);
         $this->numDoors = $numDoors;
     }

     public function getDetails(): string
     {
         return parent::getDetails().",Doors: {$this->numDoors} "; // TODO: Change the autogenerated stub
     }
}

class Motorcycle extends Vehicle{
        private  bool $hasSidecar;
        public function __construct(string $brand,string $model,bool $hasSidecar)
        {
            parent::__construct($brand, $model);
            $this->hasSidecar = $hasSidecar;
        }

        public function getDetails(): string
        {
            $sidecar = $this->hasSidecar ? "Yes" : "No";
            return parent::getDetails().",hasSidecar: {$sidecar}";
        }
}

$car = new Car ('mp','mp',4);
echo $car->getDetails()."<br>";
$motorcycle = new Motorcycle('fg','cf',false);
echo $motorcycle->getDetails();